### ISSUE TITLE
Upgrade JasperReportsLibraries to 6.7.0

### ISSUE THREAD

**Issue by daust** [daust/JasperReportsIntegration#1]
A new version of JasperReports libraries has been released on 16.10.2017 and the libraries of the integration can be upgraded now.

**Comment by jfernal** [comment]
Hello @daust i think that Jasper Reports Integration (JRI) is a very good tool, is posible use only .jrxml file? The .jasper file is compiled out and it's could raise errors, the process starts only with .jrxml file and JRI make the .jasper file, after JRI works with this file.

**Comment by jfernal** [comment]
@daust JRI could work with .jrxml code stored on a table on DB?

**Comment by jfernal** [comment]
In my work, PDF files based on an apex_collection query are the only advantage of the pl jrxml2pdf tool, but it is an incomplete tool due to limitations. I believe that these ideas can create a new powerful tool.

**Comment by daust** [comment]
Hi Fernando, 

I have moved your comments to new issues and tagged them as enhancement requests. 

Cheers, 
~Dietmar.

**Comment by jfernal** [comment]
How long could you put the new version 2.5.0?
I test now JRI 2.4.0 with .jasper file of JasperStudio 6.4.3 and works good. But is better update libraries to last stable version (final).
Regards.

**Comment by daust** [comment]
Will upgrade to latest version 6.7.0

**Comment by daust** [comment]
Well, the library itself is available in version 6.7.0: https://sourceforge.net/projects/jasperreports/files/jasperreports/

It won't take long for JasperSoftStudio to upgrade to the newer library. And compatibility in this direction (the version of the compiled .jasper files in JasperSoftStudio is lower than the runtime library) is typically no issue. 

Or would you recommend to use 6.6.0? Although I have already upgraded to 6.7.0 ;) If so, please explain why.

**Comment by jfernal** [comment]
> Well, the library itself is available in version 6.7.0: https://sourceforge.net/projects/jasperreports/files/jasperreports/
> 
> It won't take long for JasperSoftStudio to upgrade to the newer library. And compatibility in this direction (the version of the compiled .jasper files in JasperSoftStudio is lower than the runtime library) is typically no issue.
> 
> Or would you recommend to use 6.6.0? Although I have already upgraded to 6.7.0 ;) If so, please explain why.

Ohhh I didn't know about library is available in version 6.7.0
Well, it's because we always want keep the same versions on design and production to prevent errors for library versions.
But I'm happy for your new release. 
Thanks.

**Comment by daust** [comment]
Well, this is a good point and generally speaking the recommendation. But mostly to prevent using compiled .jasper files to be used in an older runtime. Probably this is a good approach to take the most current version included in JasperSoft Studio. I will do this in the future. 

Even more, I believe when implementing #2 (compiling .jrxml files on the fly) this whole issue with different versions should go away for the most part.
