### ISSUE TITLE
jasperreports pdf export encrypted Password Not Working 

### ISSUE THREAD

**Issue by HAfsari** [daust/JasperReportsIntegration#101]
#JasperReportsIntegration Server Error: 
![image](https://user-images.githubusercontent.com/14145343/153994753-b41cb03f-2eeb-4e2a-9eb0-c851fb784227.png)
 #Development Property Add
![image](https://user-images.githubusercontent.com/14145343/153995027-9e5ca99b-7750-4a16-abbe-c49b680dd861.png)

**Comment by daust** [comment]
Can you build a simple test case? Need more information. 
Where and how did you enter those attributes? Are they part of the .jrxml file now? 

It seems like a library is missing at runtime.

**Comment by daust** [comment]
This library is marked as optional. 
You can add it yourself. 

You can:
- unzip the war file: ``jar -xvf jri.war)``
- add the missing jar files to ``WEB-INF/lib/``
- zip again: ``jar -cvf jri.war *``

![image](https://user-images.githubusercontent.com/4840057/154014955-d44e6a6c-7dff-415e-9246-81f2fff90bb1.png)

Please upload a simple test case and/or describe in detail what I need to do to build a test case. 
Also, if you find and integrate the lib successfully, please let me know, I can include it into future releases.

**Comment by HAfsari** [comment]
Add dependencies > build.gradle file 
dependencies {
    //https://mvnrepository.com/artifact/com.itextpdf/itextpdf/5.5.13.2
   implementation group: 'com.itextpdf', name: 'itextpdf', version: '5.5.13.2'
  }
@daust Thanks.

**Comment by daust** [comment]
> Please upload a simple test case and/or describe in detail what I need to do to build a test case

I still need that because I am not sure, your suggestion will work. We already have a special version of itext from the JasperReports library which is based on the license-friendly version. 

So, I would rather need a test case ... so that I can make sure NOW and in the FUTURE, that everything works as expected. 

So, once again ... please a testcase!

**Comment by daust** [comment]
I have added the dependency and a sample report to the distribution and sample application: demo/encrypt-pdf

**Comment by daust** [comment]
When you configure the following properties, you can use it in your report: 
```
net.sf.jasperreports.export.pdf.encrypted=true
net.sf.jasperreports.export.pdf.128.bit.key=true
net.sf.jasperreports.export.pdf.user.password=123456
net.sf.jasperreports.export.pdf.owner.password=123456
```
This can be done through JasperSoftStudio by first selecting the report and then choosing "Advanced > Edit Properties": 
![image](https://user-images.githubusercontent.com/4840057/171997936-c5625a88-17d5-473a-84dd-392f9c3414ed.png)

Or you can add these properties directly into the .jrxml file: 
```
	<property name="net.sf.jasperreports.export.pdf.encrypted" value="true"/>
	<property name="net.sf.jasperreports.export.pdf.128.bit.key" value="true"/>
	<property name="net.sf.jasperreports.export.pdf.owner.password" value="123456"/>
	<property name="net.sf.jasperreports.export.pdf.user.password" value="123456"/>
```
