### ISSUE TITLE
Is type xlib_vc2_array_t still needed?

### ISSUE THREAD

**Issue by sweco-nldaan** [daust/JasperReportsIntegration#106]
We check for differences in our schemas between a clean installation and an upgrade.
I noticed that the xlib_vc2_array_t type was missing in a clean instalation.
I found a xlib_vc2_array_t.sql that creates that type but that script isn't called in the patch.sql or user_install.sql.
It is not dropped as well in those scripts.

Do we still need that xlib_vc2_array_t type

**Comment by daust** [comment]
No, it is not, it is old and no longer used. You are correct. I have removed it for 2.9.0. 
Thank you.
