### ISSUE TITLE
Error deploying on Wildfly application server.

### ISSUE THREAD

**Issue by sanderleget** [daust/JasperReportsIntegration#108]
With the latest issues in spring4shell we wanted to have an updated version of Jasper Reports Integration deployed. 

Tried building version 2.8.1 but this seems to no longer able to be deployed. 
While the last version we run version 2.7.1 had no problems with WildFly 22 & 26.

I did some investigation myself and tried a few options. But i ran out of idees why it no longer should work. 
Maybe u have some insight in what changed.

**Error Message:**

> {"WFLYDC0074: Operation failed or was rolled back on all servers. Server failures:" => {"server-group" => {"reporting_group" => {"host" => {"master" => {"reporting_server_one" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"JasperReportsIntegration.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.ClassCastException: class org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.jboss.logmanager.log4j.JBossLoggerContext is in unnamed module of loader 'org.jboss.logmanager.log4j2@1.1.1.Final' @621bd734; org.apache.logging.log4j.core.LoggerContext is in unnamed module of loader 'deployment.JasperReportsIntegration.war' @634b81a1)
>     Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.jboss.logmanager.log4j.JBossLoggerContext is in unnamed module of loader 'org.jboss.logmanager.log4j2@1.1.1.Final' @621bd734; org.apache.logging.log4j.core.LoggerContext is in unnamed module of loader 'deployment.JasperReportsIntegration.war' @634b81a1)
>     Caused by: java.lang.ClassCastException: class org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.jboss.logmanager.log4j.JBossLoggerContext is in unnamed module of loader 'org.jboss.logmanager.log4j2@1.1.1.Final' @621bd734; org.apache.logging.log4j.core.LoggerContext is in unnamed module of loader 'deployment.JasperReportsIntegration.war' @634b81a1)"}}}}}}}}

**WildFly Versions:**
22.0.1.final & 26.1.0.final

**Java Version:**
jdk-11.0.14.1+1

**OS Version:**
Windows Server 2012 R2

**Comment by sanderleget** [comment]
After testing with JDK 8u322-b06

I do get a similar error,

> {"WFLYDC0074: Operation failed or was rolled back on all servers. Server failures:" => {"server-group" => {"reporting_group" => {"host" => {"master" => {"reporting_server_one" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"JasperReportsIntegration.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.ClassCastException: org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
>     Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
>     Caused by: java.lang.ClassCastException: org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext"}}}}}}}}

**Comment by daust** [comment]
The bottom line on this issue was the following. We moved to log4j2 and (only) Wildfly has some automatic behavior in regard to that. Thus, it caused a conflict. After the configuration change, it works fine.
