### ISSUE TITLE
Problem verifying application over HTTPS

### ISSUE THREAD

**Issue by ogrossmann** [daust/JasperReportsIntegration#113]
I'm running JasperResportsIntegration 2.8.1 on Windows, Oracle19, APEX21 and I had problems to get a SSL connection working.

I've created a wallet and imported the certificate of the APEX server (=Oracle server). Running 
```
select apex_web_service.make_rest_request(
   p_url => 'https://my_server:8443/jri/',
   p_http_method => 'GET',
   p_wallet_path => 'file:E:\App\Oracle\admin\dinlo\wallet',
   p_wallet_pwd => 'TopSecret') as r
from dual;
```
works fine (after I learned the specific URL format).

In the APEX test application I've entered the values accordingly (the wallet path initially without "file:") and only the first 3 verification steps passed.

After I've checked the xlib_jasperreports_conf I've changed the wallet path as in my test. Now the test report and the demos are working fine while the verification steps 4 to 6 are still failing.

I haven't yet tested with another application and would so far consider the problem minor, but it would make things easier with the verification completely working and a little hint regarding the Windows path format. But the latter might be my personal problem as I might have worked too long with Java...

Thanks,
Olaf

**Comment by daust** [comment]
Thank you. Always good to make the usage smoother. 

The wallet path (using file: ) was documented here: https://github.com/daust/JasperReportsIntegration#accessing-jasperreportsintegration-through-ssl, although not that easy to find. And I use the default syntax for Oracle. 

Anyhow, should be easier, I agree. 

I have added an inline helptext for that entry field, hope that helps: 
![image](https://user-images.githubusercontent.com/4840057/186504815-0206e2e7-61e7-4116-8f6e-f12b16eb2723.png)

Also, I have checked the "Verify Setup" tests, and they should work better now.

**Comment by ogrossmann** [comment]
Thanks a lot Dietmar,

But I have another and totally unrelated question: Would it be possible to make the isIgnorePagination parameter available through the API? Right now I use a copy of each report with isIgnorePagination="true" for the output to Excel or HTML but it would be more convenient to have a single report file.

Thanks again,
Olaf

PS: I guess I could write in German? I didn't meet so many Dietmars before but all were German ;-)

**Comment by daust** [comment]
Hallo Olaf, 

ja, Deutsch geht natürlich auch :). 
But so that all people understand what we are discussing, let's use English here on that platform. 

I have taken your suggestion and created a new enhancement request for it: https://github.com/daust/JasperReportsIntegration/issues/122

Liebe Grüße
~Dietmar.
