### ISSUE TITLE
Deploying jri.war file on Oracle Weblogic Server

### ISSUE THREAD

**Issue by inderjeetfbd** [daust/JasperReportsIntegration#118]
Hi,

We are receiving following error while trying to deploy the jri.war file on Oracle Weblogic Server 12c.

![image](https://user-images.githubusercontent.com/23182481/192434675-01ecf83e-8605-4de5-ab48-605a4e98a5fa.png)

Please suggest.

Thanks
Inder.

**Comment by daust** [comment]
@inderjeetfbd , do you still have this issue? 
I typically don't use/test on Weblogic Server.

**Comment by inderjeetfbd** [comment]
Yes, the problem still persists.

**Comment by daust** [comment]
OK, then please provide more details: 
- jri.war ... EXACT version
- Java /JDK version that is being used by Weblogic

Thank you.

**Comment by kboughdiri** [comment]
I have the same problem.
+ jri.war is the last version 2.10
+JDK used by WebLogic is 1.8.0_151

**Comment by inderjeetfbd** [comment]
Hi,

Here are the requested details.

1. Exact version of jri.war - v2.8.1
2. Java version - 1.8.0_202

Thanks
Inder.

**Comment by daust** [comment]
This is really weird. 

When you change the ``web.xml`` file in (``jri.war/WEB-INF``) from 
```
<web-app id="WebApp_ID" version="2.4"
	xmlns="https://java.sun.com/xml/ns/j2ee"
	xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://java.sun.com/xml/ns/j2ee https://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
```
to 
```
<web-app id="WebApp_ID" version="2.4">
```
it starts working

You can fix the existing version for Weblogic manually, I have fixed it for the next release 2.11.0. 

Best
~Dietmar.

**Comment by daust** [comment]
This is really weird. The original setting was correct, only Weblogic cannot deal with the https part. Thus, I changed it from https to http ... and now it works in all environments. Looks like a Weblogic bug to me. 
Anyhow, it is fixed and tested on Tomcat 9 and 10, Weblogic (12 and 14) and Wildfly 26.1.

**Comment by inderjeetfbd** [comment]
Hi Daust,

Thank you for your reply. I will try it out and let you know as well.

Thanks
Inder.
