### ISSUE TITLE
Error when running from APEX 21.2.8

### ISSUE THREAD

**Issue by rv8470** [daust/JasperReportsIntegration#120]
Hello,

I am trying to get the kit working on our environment. We have SSL security and the check runs fine. When I want to execute it from an APEX app the system comes back with an error: **Error: SyntaxError: Unexpected token '<', " <!-- Copyr"... is not valid JSON**
Not sure what is wrong here. We are using Tomcat 9 with JDK 17 on windows server 2019. See for more details some screen shots attached.

Regards,
[JasperReportsIntegrationError.pdf](https://github.com/daust/JasperReportsIntegration/files/10020738/JasperReportsIntegrationError.pdf)

Rob

**Comment by rv8470** [comment]
Solved it by using http settings instead of https

**Comment by daust** [comment]
This is strange, was this the only thing you changed, switching from https to http?
It looks a little bit like the issue when pages are not submitted but only processed using an AJAX call. 

Setting the page configuration parameter ``Reload on Submit = Always`` fixes that ... but causes issues with Interactive Grids for example. 
![image](https://user-images.githubusercontent.com/4840057/205256942-3dc97491-672a-4d4b-962a-42b8f621d8ae.png)

**Comment by daust** [comment]
Hi Rob, 
I did just check in my environment and it all works with https. 
Can you test it using https and then run one of the demo reports? 
Thank you. 

Like this: 
![image](https://user-images.githubusercontent.com/4840057/205262937-ce2a3572-5f53-42fd-905e-606a75b7b29f.png)

![image](https://user-images.githubusercontent.com/4840057/205262970-375cdb36-914d-4a24-9348-076639230778.png)

![image](https://user-images.githubusercontent.com/4840057/205263122-91424714-5eb7-4e37-80c2-9e647b5c763e.png)

**Comment by rv8470** [comment]
Hi Dietmar,

Thanks for your replies. 

In the first place I started with the generation of PDF outputs using PL/SQL, that was fixed with the http setting. The other issue with the APEX error was indeed fixed by the "Reload on Submit" setting for displaying the output in the browser. I was informed by another developer, he had experienced the same issue.

So it's working fine now

Thanks

**Comment by daust** [comment]
Wonderful. Glad that you have it working now :)
