### ISSUE TITLE
Oracle OCI and Datasource

### ISSUE THREAD

**Issue by wahidali01** [daust/JasperReportsIntegration#134]
i have an issue with the oracle oci database and data source 
[datasource:ryan]
type=jdbc
name=ryan
url=jdbc:oracle:thin:@tnsnames_entry?TNS_ADMIN=/home/opc/wallet
username=HR
password=HR_PASSWORD

Error : 
Message Could not connect via JDBC: IO Error: Invalid connection string format, a valid format is: "host:port:sid"

**Comment by daust** [comment]
Hi @wahidali01, 

this is strange, the syntax looks correct. 

Please provide more details: 
- JRI version
- Database version you are connecting to ... I guess the recent Oracle cloud, right? Which version is that currently? 
- Operating system of your application server
- application.properties file (you can mask any passwords)
- logfile

you can also mail these files to dietmar.aust@gmail.com

Thank you
~Dietmar.

**Comment by daust** [comment]
Ok, thank you. Then I will close this issue, the syntax looks ok. 
Should you get another account and have this issue again, please reopen this ticket or create another one. Thank you and all the best, Dietmar.
