### ISSUE TITLE
Application at context path [/jri] could not be started

### ISSUE THREAD

**Issue by abilalshah** [daust/JasperReportsIntegration#144]
Hi

After configuring jri-2.11.0-jasper-6.20.6-tomcat10.war in tomcat webapps, it could not start and giving this message.
FAIL - Application at context path [/jri] could not be started

**Environment:**
Windows Server 2022
JDK 19
apache-tomcat-10.1.24
jri-2.11.0-jasper-6.20.6

What could be the issue.
Please help

Thanks

**Comment by abilalshah** [comment]
Issue has been resolved.

**Comment by KElsayed2** [comment]
Dear abilalshah ..
Hope you're doing fine.

I'm facing the same problem .. Kindly could you advice about the solution.

Thanks.
Regards.

**Comment by abilalshah** [comment]
> Dear abilalshah .. Hope you're doing fine.
> 
> I'm facing the same problem .. Kindly could you advice about the solution.
> 
> Thanks. Regards.

I resolved the issue by using JRI path from 
C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\jri 
instead of using from 
C:\OracleDB\JRI

Regards

**Comment by KElsayed2** [comment]
Dear abilalshah,

Appreciated your feedback.

Many Thanks.
