### ISSUE TITLE
Periodic CPU load within Tomcat when JRI running

### ISSUE THREAD

**Issue by PeterPSSE** [daust/JasperReportsIntegration#16]
The Tomcat service process generates high CPU load every 10 seconds (for about 1-2 seconds) whenever JasperReportsIntegration is active (Running=true). This originates from periodically reloading all jar-Files under 

   "...JasperReportsIntegration\WEB-INF\lib\"

due to your setting Reloadable="true" in 

   "...JasperReportsIntegration\META-INF\context.xml"

Please provide an improved context.xml as an installation default file. Nevertheless JRI is a great tool!
Regards
Peter

**Comment by daust** [comment]
Hi Peter, thanks for investigating this one with me. It is not really a bug but creates way too much work on the Tomcat. 

I have fixed this and will include it into the next release of JRI.

**Comment by daust** [comment]
Just to properly document the issue. The spike was due to Tomcat re-scanning all *.jar files in the JasperReportsIntegration.war/WEB-INF/lib directory. This was due to the parameter reloadable="true" in the <Context definition. 

This has been fixed in the context.xml file.
