### ISSUE TITLE
Wrong ojdbc library used causing connection failure

### ISSUE THREAD

**Issue by richardchallis** [daust/JasperReportsIntegration#17]
I have a found (and have a temp fix) regarding the JasperReports Integration config, which I thought I would pass back to you (and if the temp fix should be done better, let me know !)
I have downloaded and installed the 2.5.0.1 Beta release, and in the conf/application.properties file I have configured the jdbc string as follows :
 
#====================================================================
# JDBC datasource configuration
# http://www.orafaq.com/wiki/JDBC#Thin_driver
# type=jdbc|jndi
#====================================================================
[datasource:default]
type=jdbc
name=default
url= jdbc:oracle:thin:@localhost:1539/xepdb1
username=testjasper
password= testjasper
 
I’m running Oracle 18xe database on Oracle Linux and using Tomcat 7 app server. Due to running a pluggable database the end of the jdbc connection is /servicename rather than :SID). I’ve checked that the jdbc string is correct via both the command line (using the instructions posted on https://comm.support.ca.com/kb/how-to-test-jdbc-connection-to-an-oracle-server/kb000106561 , and I have a community jasperreports installation which also uses the same format jdbc with ojdbc8.jar as the oracle driver (same file, filesize etc as that in your jasperserverintegration/lib directory ))as follows :-
# java -jar ./jdbc-tester-1.0.jar testjasper testjasper jdbc:oracle:thin:@localhost:1539/xepdb1
11:42:42.530 [main] INFO Main - arg 0 = testjasper
11:42:42.536 [main] INFO Main - arg 1 = testjasper
11:42:42.536 [main] INFO Main - arg 2 = jdbc:oracle:thin:@localhost:1539/xepdb1
11:42:42.680 [main] INFO Main - ****** Starting JDBC Connection test *******
11:42:43.147 [main] INFO Main - Running SQL query: [select sysdate from dual]
11:42:43.170 [main] INFO Main - Result of sql Query: [2018-11-30 11:42:43.0]
11:42:43.170 [main] INFO Main - JDBC connection test successful!
 
However, when I run the test report, I get an “http 500” error

So, in digging round, in the deployed app directory (WEB-INF/lib), I could see 3 ojdbc.jar files ojdbc14.jar, ojdbc6.jar and ojdbc8.jar) Knowing that I needed ojdbc8.jar, I renamed the other two files (added a suffix.temp), and then restarted the application.
 
In doing so, the test pages and test jdbc commands work. Is there a “better” way to fix this ?

**Comment by PeterPSSE** [comment]
yes, delete the files ojdbc6.jar and ojdbc14.jar ;-)  So do I.
