### ISSUE TITLE
JRStyledTextParser with font Noto Sans CJK SC from Google

### ISSUE THREAD

**Issue by midval** [daust/JasperReportsIntegration#18]
Hi Dietmar,

We want generate reports with chinese signs. Therefore we are using Google font "Noto". When I create the report with JasperStudio 6.2 and have the font included in the build path as a jar file. Everything is fine and the font is also embedded into the PDF.
When we then copy the jar file to the path /WEB-INF/lib where jasperreoprtsintegration is installed and start tomcat, we can not generate any pdf. It throws the following error:
"java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.engine.util.JRStyledTextParser".
I tried different things I found on google, but nothing helps.
May you know what I'm doing wrong? I'm wondering because when I run the report with JasperStudio everything is fine just with the JRI service it generates this error.

Font link:
https://www.google.com/get/noto/help/cjk/
NotoSansCJKsc-[weight].otf and NotoSansMonoCJKsc-{Regular, Bold}.otf

Regards Lavdim

**Comment by daust** [comment]
Hi @midval, 

did you install the fonts as described here: https://www.google.com/get/noto/help/install/ ?

The fonts need to be properly installed on the target application server machine, so that Java can access them. 

Thanks
~Dietmar.

**Comment by daust** [comment]
I am closing this issue because the op didn't respond. If you still encounter this issue, please reopen the issue. Thanks.
