### ISSUE TITLE
Issue with URL construct on JRI 2.5.0.1 (beta) and quickfix

### ISSUE THREAD

**Issue by igorfilko** [daust/JasperReportsIntegration#19]
Hi all!

Using JRI 2.5.0.1 with Oracle 12c (12.2.0.1) and APEX 18.2 (ORDS 18.3/Tomcat9).

There is a issue with XLIB_JASPERREPORTS package on 2.5.0.1 with URL construct for upper configuration. It seems that during instalation code got garbled a bit and package during execution
mixed up the URL so the result was
`"http://JRIServer:8080/JasperReportsIntegration/report?_repName=zaduznice_mobiteli=pdf=default=zaduznica.pdf=en_US=windows-1250==wwv_flow%2Eshow%3Fp_request%3DAPPLICATION_PROCESS%253DJRI_SHOW_IMAGE%3D600%3D0%3D13190477698931%3D%23IMAGE_NAME%23=false===1=false=false==false=&Parameter1=120"`
so I found the original code in package prior to sys_install and user_install and copy&paste fixed the code on get_report and show_report.

With these changes, JRI 2.5.0.1 (beta) works on upper configuration.

Code for get_report (lines 328-365)

```
      -------------------------------------------------------
      -- construct URL
      -------------------------------------------------------
      l_url := m_report_url;
      l_url := l_url || '?_repName=' || p_rep_name;
      l_url := l_url || '&_repFormat=' || p_rep_format;
      l_url := l_url || '&_dataSource=' || p_data_source;
      l_url := l_url || '&_repLocale=' || p_rep_locale;
      l_url := l_url || '&_repEncoding=' || p_rep_encoding;
      l_url := l_url || '&_repTimeZone=' || APEX_UTIL.URL_ENCODE(p_rep_time_zone);

      -- per default use the tunnel through the database
      if m_images_uri is null or m_images_uri = c_images_uri_tunnel then
        -- tunnel through database
        l_url := l_url || '&_imagesURI=' || APEX_UTIL.URL_ENCODE(compute_images_uri_tunnel);
      else
        -- use parameter, mostly for direct access to servlet
        l_url := l_url || '&_imagesURI=' || APEX_UTIL.URL_ENCODE(m_images_uri);
      end if;
      
      -- direct printing
      l_url := l_url || '&_printIsEnabled=' || bool2string(p_print_is_enabled);
      l_url := l_url || '&_printPrinterName=' || p_print_printer_name;
      l_url := l_url || '&_printPrinterTray=' || p_print_media;
      l_url := l_url || '&_printCopies=' || p_print_copies;
      l_url := l_url || '&_printDuplex=' || bool2string(p_print_duplex);
      l_url := l_url || '&_printCollate=' || bool2string(p_print_collate);
      l_url := l_url || '&_printJobName=' || p_print_job_name;
      
      -- save file on server
      l_url := l_url || '&_saveIsEnabled=' || bool2string(p_save_is_enabled);
      l_url := l_url || '&_saveFileName=' || p_save_filename;
      
      -- additional report parameter passed?
      IF (p_additional_params IS NOT NULL)
      THEN
         l_url := l_url || '&' || p_additional_params;
      END IF;
```
and for show_report (lines 247-285)

```
      -------------------------------------------------------
      -- construct URL
      -------------------------------------------------------
      l_url := m_report_url;
      l_url := l_url || '?_repName=' || p_rep_name;
      l_url := l_url || '&_repFormat=' || p_rep_format;
      l_url := l_url || '&_dataSource=' || p_data_source;
      l_url := l_url || '&_outFilename=' || p_out_filename;
      l_url := l_url || '&_repLocale=' || p_rep_locale;
      l_url := l_url || '&_repEncoding=' || p_rep_encoding;
      l_url := l_url || '&_repTimeZone=' || APEX_UTIL.URL_ENCODE(p_rep_time_zone);

      -- per default use the tunnel through the database
      if m_images_uri is null or m_images_uri = c_images_uri_tunnel then
        -- tunnel through database
        l_url := l_url || '&_imagesURI=' || APEX_UTIL.URL_ENCODE(compute_images_uri_tunnel);
      else
        -- use parameter, mostly for direct access to servlet
        l_url := l_url || '&_imagesURI=' || APEX_UTIL.URL_ENCODE(m_images_uri);
      end if;
      
      -- direct printing
      l_url := l_url || '&_printIsEnabled=' || bool2string(p_print_is_enabled);
      l_url := l_url || '&_printPrinterName=' || p_print_printer_name;
      l_url := l_url || '&_printPrinterTray=' || p_print_media;
      l_url := l_url || '&_printCopies=' || p_print_copies;
      l_url := l_url || '&_printDuplex=' || bool2string(p_print_duplex);
      l_url := l_url || '&_printCollate=' || bool2string(p_print_collate);
      l_url := l_url || '&_printJobName=' || p_print_job_name;
      
      -- save file on server
      l_url := l_url || '&_saveIsEnabled=' || bool2string(p_save_is_enabled);
      l_url := l_url || '&_saveFileName=' || p_save_filename;
      
      -- additional report parameter passed?
      IF (p_additional_params IS NOT NULL)
      THEN
         l_url := l_url || '&' || p_additional_params;
      END IF;
```

**Comment by daust** [comment]
I don't quite understand. When I look at the distributed source code ... everything looks fine. How could the installation go wrong here?

**Comment by daust** [comment]
Hi @igorfilko : Do you still have any issues here ... or can I close the issue? Thanks.

**Comment by igorfilko** [comment]
Hi Dietmar!

You can close this issue. I have no idea why that happened but I copy&pasted original code from sql file and its just fine.

BR,

Igor Filko, univ.spec.oec., struč.spec.ing.techn.inf., ing.inf.
Voditelj Odjela za korisničku podršku

[cid:image001.jpg@01D68B35.92AFA340]
SLUŽBA ZA INFORMATIKU
31000 OSIJEK, ŠETALIŠTE KARDINALA FRANJE ŠEPERA 1A
Odjel za korisničku podršku
Tel: 031/244013, INT: 254013
Mob: 091/2440310, VPN: 8910
Email: igor.filko@hep.hr, www.hep.hr

IZJAVA O ODRICANJU ODGOVORNOSTI: Sadržaj ove poruke i eventualno priloženih datoteka povjerljiv je, te namijenjen isključivo osobama ili subjektima koji su navedeni kao primatelji. Ukoliko je zbog greške pri adresiranju ili prijenosu ova poruka pogrešno upućena, molimo Vas obavijestite pošiljatelja slanjem odgovora na ovu poruku, a poruku i sve njene priloge odmah, bez čitanja, trajno uklonite s računala. Svako neovlašteno korištenje, objavljivanje, prerada, obrada, reprodukcija, prikazivanje, prenošenje, distribucija, snimanje ili bilo koji drugi oblik neovlaštene uporabe ove poruke je zabranjeno te može biti zakonski kažnjivo. Sadržaj, stavovi i mišljenja izneseni u poruci su autorovi te nužno ne predstavljaju stav ili mišljenje društva HEP–Operator distribucijskog sustava d.o.o. Pored toga, HEP–Operator distribucijskog sustava d.o.o. ne prihvaća nikakvu odgovornost za eventualnu štetu nastalu primitkom ove poruke te priloga sadržanih u poruci.

DISCLAIMER OF LIABILITY STATEMENT: The contents of this message and possibly annexed data are confidential and intended exclusively for the persons or subjects which are listed as recipients. If this message was due to a mistake in addressing or transfer sent to you by mistake, please inform the sender by replying to this message, and the message and all its contents immediately, and without reading it, permanently remove from the computer. Each unauthorized use, publication, processing, reproduction, presentation, transfer, distribution, recording or any other form of unauthorized use of this message is prohibited and can be punished by law. The contents, positions and opinions stated in the message belong to the author and do not necessarily belong to the HEP – Operator distribucijskog sustava d.o.o.. In addition, HEP – Operator distribucijskog sustava d.o.o. does not accept any liability for possible damages caused by the receipt of this message and the annexes contained in the message

**Comment by daust** [comment]
Perfect 👍 . I will close the issue. Thanks.
