### ISSUE TITLE
Printing of Slovenian characters - Č

### ISSUE THREAD

**Issue by AlesHafner** [daust/JasperReportsIntegration#21]
Hello!

I started using JasperReportsIntegration / 2.4.0 on the Tomcat server and Apex 5.1.
The printout is beautifully displayed only for missing special characters like "Č".

rep_locale: sl_SI
p_rep_encoding: Windows-1250

I ask for instructions on what I need to do to display these characters.
Thank you!

**Comment by jdemovic** [comment]
Hi,
I use the same version of the JRI and everytings goes fine.
rep_locale: default (DE_de)
p_rep_encoding: UTF-8
JRXML file header:
![obrazek](https://user-images.githubusercontent.com/14126765/68458851-08dc4700-0204-11ea-8c59-fa84585a1660.png)

I use it for SVK chars - similar to SLO :)

Regards
J

**Comment by daust** [comment]
Hi @AlesHafner : Did that fix your issue? Or do you need more help?

**Comment by daust** [comment]
I am closing this issue because the op didn't respond. If you still encounter this issue, please reopen the issue. Thanks.
