### ISSUE TITLE
show_report parameter p_out_filename issue downloading the report automatically

### ISSUE THREAD

**Issue by golfmeister2005** [daust/JasperReportsIntegration#22]
I'm using JasperReportsIntegration 2.4.0.0.

If I call the show_report and pass NULL to p_outfilename the report displays in PDF which is great. If I click the download button it default the name to f.pdf

I want to change the default name to something else so I tried I'm passing the default report name like 'myreport.pdf' to p_outfilename. 

The issue is when you run the report it downloads the file but you get an empty all white blank space.

Thanks

**Comment by BernhardFW** [comment]
I think you hv to use the parameters such as:

xlib_jasperreports.show_report (p_rep_name => 'my_jasper_report',
                                  p_rep_format => 'pdf', --:P2_REP_FORMAT,
                                  p_data_source => 'my_datasource',
                              --    p_out_filename => 'myreport.pdf',                            <----- or as below
                                  p_out_filename => 'myReportt_'||:P2_order:nr||'.pdf',   <-------
                                  p_rep_locale => 'de_DE',
                                  p_rep_encoding => 'UTF-8',
                                  p_additional_params => l_additional_parameters);
late.. but I hope that helps... I just came across this...

**Comment by daust** [comment]
@golfmeister2005 : Did that fix your issue?

**Comment by daust** [comment]
I am closing this issue because the op didn't respond. If you still encounter this issue, please reopen the issue. Thanks.
