### ISSUE TITLE
Error while using p_save_is_enabled option

### ISSUE THREAD

**Issue by rajeshwari87** [daust/JasperReportsIntegration#23]
Hi,
I am using oracle apex 18 and have integrated jasper reports. When i enable p_save_is_enabled parameter and click on get report as blob and show, file is download properly but report is not shown and page shows below error. Kindly help how to download pdf and display in application also.

HTTP Status 500 – Internal Server Error
Type Exception Report

Message Stream Closed

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

ExceptionConverter: java.io.IOException: Stream Closed
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.17

**Comment by daust** [comment]
Are you still experiencing this issue?

**Comment by daust** [comment]
I am closing this issue because the op didn't respond. If you still encounter this issue, please reopen the issue. Thanks.
