### ISSUE TITLE
I want to use barcodes and this feature cause a null pointer exception

### ISSUE THREAD

**Issue by jfernal** [daust/JasperReportsIntegration#24]
I want to use barcodes and this feature cause a null pointer exception. 
Maybe, Could you update the libraries??

**Comment by daust** [comment]
I need more information here. 

I have just updated the jasperreports libraries to 6.14.0, the latest release. You can download the pre-release soon, by the end of the week I assume. 

Cheers
~Dietmar.

**Comment by daust** [comment]
I am closing this issue because the op didn't respond. If you still encounter this issue, please reopen the issue. Thanks.
