### ISSUE TITLE
SOLVED: store pdf directly in BLOB without open it in browser

### ISSUE THREAD

**Issue by BernhardFW** [daust/JasperReportsIntegration#25]
Hi Dietmar,
I like to store the pdf into a BLOB without opening it in a browser.

I did use ur code:

`DECLARE
   l_blob        BLOB;
   l_mime_type   VARCHAR2 (100);
     l_proc varchar2(100) := 'get report as blob, then show';
BEGIN
   xlog (l_proc, 'url (orig):' || :g_report_url);
      ------------------------------------------------------------------------
   -- generate the report and return in BLOB
   ----------------------------------------------------------------------------
...... and further down:
-- set content length
   ------------------------------------------------------------------------
   HTP.p ('Content-length: ' || DBMS_LOB.getlength (l_blob));
   OWA_UTIL.http_header_close;
   ------------------------------------------------------------------------
   -- download the file and display in browser
   ------------------------------------------------------------------------
   WPG_DOCLOAD.download_file (l_blob);  <-------------------------
   ----------  store in table-----

    insert into MY_TABLE (
      dateiname
    , mimetype
    , image
    ) values (
      'My_report'.pdf'
    , 'application/pdf'
    , l_blob
    );
    commit;`

what can I use instead of  "WPG_DOCLOAD.download_file (l_blob);" ???

avoiding the browser download... BUT save in BLOB ?

thanks

BTW: you shud have an "DONATION" button somewhere...

**Comment by BernhardFW** [comment]
SOLVED by myself:
I commented out all htp and download related features... then it does work.
as per ORCL doc DBMS_LOB temporary lobs are freed at the end of a session... I hope that is sufficient
thanks

**Comment by daust** [comment]
Hi Bernhard, 

yes, this is the correct way to do it. 

Hopefully, I will find the time to make it more transparent in the documentation. 

Best regards
~Dietmar
