### ISSUE TITLE
Connecting to ATP Database

### ISSUE THREAD

**Issue by sb20200428** [daust/JasperReportsIntegration#26]
Dietmar - 

Interested in connecting JRI to an Oracle Cloud Automated Transaction Processing DB  instance.  The XLIB database objects have all been installed.  Have a Tomcat instance running on a compute VM for the JRI web app.   Configured datasource and tested - all I'm getting are repeated "NL Exception was generated" errors.  I do not believe it to be an ACL or firewall issue.  

Noticed that the 'oraclepki.jar', 'osdt_core.jar', etc. JARs have been loaded into the lib folder, so I figure that you may have a provision for connecting via Oracle Wallet.  

Using following db connection string in 'application.properties': 
db=jdbc:oracle:thin:@dbid_medium?TNS_ADMIN=/path/to/wallet

Can you provide guidance?  It would be greatly appreciated.  Have had success using your toolkit in past - but they were always local applications.  I would like to see how it works w/ a cloud application.

**Comment by daust** [comment]
Hi. 

Unfortunately, I have no experience with this specific setup. 

Did you figure it out in the meantime? Is this problem still relevant for you ... or did you find another solution? 

Thanks
~Dietmar.

**Comment by sb20200428** [comment]
Yes, still interested.  No, did not find a solution beyond moving away from JRI.  I suppose, to simplify, the question would be whether or not JRI can be made to work using oracle wallet authentication.

**Comment by daust** [comment]
I don't see any reason why it should not work when I look at the instructions: https://www.oracle.com/database/technologies/java-connectivity-to-atp.html

Starting with version 2.6.0 we are using the right jdbc library to support that. But we might need to pick up a different set of jdbc libraries which also includes more security related support: https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19c-downloads.html

Once I have updated the documentation and released 2.6.0 I will have a look at this and give it a try.

**Comment by daust** [comment]
it is now fixed and works. I downloaded the right version to support cloud connections from: https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19c-downloads.html:
```
ojdbc8-full.tar.gz
```
