### ISSUE TITLE
error connection database on 2.5.0.1

### ISSUE THREAD

**Issue by rortin** [daust/JasperReportsIntegration#28]
hi, i have install and configure on centos 7 with the las oracle XE.
Jasperreport server is online, but when i go to do a test its say this:

java.lang.RuntimeException: Could not connect via JDBC: Excepción de E/S: Invalid connection string format, a valid format is: "host:port:sid" 

in application.properties i have:

url=jdbc:oracle:thin:@127.0.0.1:1539\XEPDB1

where XEPDB1 is my service
i cant connect with this configuration on Ireport and sqldeveloper.

Can you help me??

Thanks

**Comment by rortin** [comment]
impossible, i have to intall a new server with oracle 18c xe, apex 20.1, ords and Jasperreportintegration.

If i write: url=jdbc:oracle:thin:@127.0.0.1:1539/XEPDB1  in my config, its said the same... 

java.lang.RuntimeException: Could not connect via JDBC: Excepción de E/S: Invalid connection string format, a valid format is: "host:port:sid"

And if i put the correct string:  url=jdbc:oracle:thin:@127.0.0.1:1539:XEPDB1, its sais:

"ORA-12505, TNS:listener does not currently know of SID given in connect descriptor"  

if i put de XE SID:  url=jdbc:oracle:thin:@127.0.0.1:1539:XE

"Could not connect via JDBC: ORA-28040: No coincide ningún protocolo de autenticación"

The service is valid, because i start with it sqldeveloper and ireport, so ...
i havent no ideas.... some one more????

**Comment by rlljorge** [comment]
> impossible, i have to intall a new server with oracle 18c xe, apex 20.1, ords and Jasperreportintegration.
> 
> If i write: url=jdbc:oracle:thin:@127.0.0.1:1539/XEPDB1 in my config, its said the same...
> 
> java.lang.RuntimeException: Could not connect via JDBC: Excepción de E/S: Invalid connection string format, a valid format is: "host:port:sid"
> 
> And if i put the correct string: url=jdbc:oracle:thin:@127.0.0.1:1539:XEPDB1, its sais:
> 
> "ORA-12505, TNS:listener does not currently know of SID given in connect descriptor"
> 
> if i put de XE SID: url=jdbc:oracle:thin:@127.0.0.1:1539:XE
> 
> "Could not connect via JDBC: ORA-28040: No coincide ningún protocolo de autenticación"
> 
> The service is valid, because i start with it sqldeveloper and ireport, so ...
> i havent no ideas.... some one more????

I have the same issue .
@rortin do you can resolve this ?

**Comment by ViktorAfnt** [comment]
Try to delete the ojdbc14.jar file. 
Use ojdbc6.jar or ojdbc8.jar instead it. 
See What are the Oracle JDBC releases Vs JDK versions?

**Comment by rlljorge** [comment]
> Try to delete the ojdbc14.jar file.
> Use ojdbc6.jar or ojdbc8.jar instead it.
> See What are the Oracle JDBC releases Vs JDK versions?
Hi 
I switched between version for jdbc without success.
I did downgrade from openjdk 11 to openjdk 8, same problem.
I check the compatibility matrix in https://www.oracle.com/database/technologies/faq-jdbc.html and I din't see any problem.

**Comment by rlljorge** [comment]
@ViktorAfnt  sorry my mistake, I removed file ojdbc in wrong paths .. 

Now I removed  ojdbc14.jar ojdbc6.jar in /usr/local/tomcat/webapps/JasperReportsIntegration/WEB-INF/lib and I can execute test connection with success using de JDBC url=jdbc:oracle:thin:@MY_DBSERVER:1521/XEPDB1 

I used the connection teste url http://servername:8080/JasperReportsIntegration/test?_dataSource=default  with success but all reports return blank page. 

URL to report TEST:
http://servername:8080/JasperReportsIntegration/report?_repName=test&_repFormat=pdf&_dataSource=default&_outFilename=&_repLocale=&_repEncoding=&_repTimeZone=&_printIsEnabled=&_printPrinterName=&_printJobName=&_printPrinterTray=&_printCopies=&_printDuplex=&_printCollate=&_saveIsEnabled=&_saveFileName=

I didn't see any errors in logs, have some ideia ?

**Comment by rlljorge** [comment]
@ViktorAfnt perfect using only ojdbc8.jar works fine ! Thank you !

**Comment by daust** [comment]
The upcoming release will include updated libraries for ojdbc8 supporting Oracle 19+ databases.
