### ISSUE TITLE
JasperReportsIntegration with PostgreSQL

### ISSUE THREAD

**Issue by ViktorAfnt** [daust/JasperReportsIntegration#29]
Hi,
I tested JasperReportsIntegration 2.5.0.0 with Oracle, it was ok. But with PostgreSQL was no luck.
There's postgresql-42.2.14.jar in \lib directory.
application.properties:
#============================================================
[datasource:default]
type=jdbc
name=default
url=jdbc:oracle:thin:@x.x.x.x:1521/ordb
username=usr
password=pw
#============================================================ [datasource:postgresql]
type=jdbc
name=postgresql
url=jdbc:postgresql://x.x.x.x:5432/pgdb
username=user
password=pw
#============================================================
 
I start http://localhost:8090/JasperReportsIntegration/
and click on the line 'postgresql  jdbc  Test'
and receive the message:

java.lang.RuntimeException: Could not connect via JDBC: ????? ???????? URL Oracle
(Invalid Oracle URL specified)

Why Oracle URL? I use Postgresql.
Because Class.forName("oracle.jdbc.driver.OracleDriver")?
But With JDBC 4.0, applications no longer need to issue a Class.forName() on the driver name; instead, the DriverManager will find an appropriate JDBC driver when the application requests a Connection. 

Can you help me, please?

**Comment by daust** [comment]
Hi Viktor, 

I will close this ticket with the reference to your forum post, where you detail your solution: https://gitq.com/daust/JasperReportsIntegration/topics/13/jasperreportsintegration-with-postgresql

Thanks a lot for your contribution 👍 

Dietmar.
