### ISSUE TITLE
Report Parameter Data type Integer (java.lang.String cannot be cast to java.lang.Integer)

### ISSUE THREAD

**Issue by HAfsari** [daust/JasperReportsIntegration#56]
#Parameter Data Type Custing Error
![image](https://user-images.githubusercontent.com/14145343/95553330-29260e80-0a30-11eb-8326-fb726a1ee727.png)

Also, Jasper SCRIPTLET Integer type parameter Casting Conver Error
-------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/14145343/95554416-f7ae4280-0a31-11eb-87ab-fa0b120e45af.png)

**Comment by daust** [comment]
1. Can you upload the report definition? Or ideally build a simplified test case which I can run locally?
2. Is this a new issue with the new release and was working before? Or is this a new / changed report? 
3. Is it possible that the parameter is defined as Number/Integer? The integration can ONLY work with "String". In the sql query you would use ``to_number()`` to use it as a number.

**Comment by HAfsari** [comment]
REPORT SOURCE FILE PARAMETTER pausit_id Integer 
want to param data type integer & data conver to_number() requried Migration?
----------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="test" pageWidth="595" pageHeight="842" whenNoDataType="BlankPage" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="2f5542fa-3633-4ed3-b168-f3ac22a02298">
	<property name="com.jaspersoft.studio.data.sql.tables" value=""/>
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="TAHQIQ_DEV"/>
	<scriptlet name="REPORT_TAHQIQ" class="com.mislbd.tahqiq.TahqiqScriptlet">
		<scriptletDescription><![CDATA[Tahqiq Java Project Report Application]]></scriptletDescription>
	</scriptlet>
	<parameter name="paudit_id" class="java.lang.Integer"/>
	<queryString language="SQL">
		<![CDATA[select 'AAAAAAAAAAAAAAA'  DATA from DUAL where 1 = $P{paudit_id}]]>
	</queryString>
	<field name="DATA" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.label" value="DATA"/>
	</field>
	<background>
		<band splitType="Stretch"/>
	</background>
	<detail>
		<band height="30" splitType="Stretch">
			<textField textAdjust="StretchHeight" isBlankWhenNull="true">
				<reportElement stretchType="ContainerBottom" x="0" y="0" width="555" height="30" isPrintWhenDetailOverflows="true" uuid="8a4962c6-398f-4d6f-9c36-e33e4e9270c2">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="97b0d215-6655-4d49-b3d2-c09c736c21a4"/>
				</reportElement>
				<box>
					<pen lineWidth="0.25"/>
				</box>
				<textElement textAlignment="Center">
					<font fontName="Times New Roman" size="14"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{DATA}]]></textFieldExpression>
			</textField>
		</band>
	</detail>
</jasperReport>

**Comment by HAfsari** [comment]
Parameter paudit_id Integer

**Comment by daust** [comment]
Hi @HAfsari, as I said before and like the documentation states, only parameters of type STRING are allowed, you are using Integer. This is currently unsupported. 

https://github.com/daust/JasperReportsIntegration/blob/master/src/doc/github/integration-usage.md

![image](https://user-images.githubusercontent.com/4840057/95715820-c1a7d300-0c6a-11eb-82c9-2484d3a053e2.png)
