### ISSUE TITLE
Jasperreportsintegration on linux and autonomus database

### ISSUE THREAD

**Issue by har3653** [daust/JasperReportsIntegration#74]
Hi can you give me example for jdbc conection string for conection with autonomus database, i tried to conect using documentation provided but not successfuly.

**Comment by daust** [comment]
What exactly did you try? Can you copy the exact string here? 

This did not work?
```
[datasource:default]
name=default
url=jdbc:oracle:thin:@tnsnames_entry?TNS_ADMIN=/path/to/wallet
username=MY_USER
password=my_user_password
```

Did you get an error message?

**Comment by har3653** [comment]
Here is the connection string 

url=jdbc:oracle:thin:@cloud_high?TNS_ADMIN=/tmp/wallet/

and here is the error

HTTP Status 500 – Internal Server Error
Type Exception Report

Message Could not connect via JDBC: IO Error: The Network Adapter could not establish the connection

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.RuntimeException: Could not connect via JDBC: IO Error: The Network Adapter could not establish the connection
	de.oc.utils.Utils.throwRuntimeException(Unknown Source)
	de.oc.db.ConnectionUtility.getConnection(Unknown Source)
	de.oc.integration.jasper.webapp.AppConfig.getConnection(Unknown Source)
	de.oc.integration.jasper.webapp.ReportWrapper.service(Unknown Source)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.44

im using  odbc8
system : oracle linux 7
oracle cloud VM instance
opened 1522 port 


I tried both ways of conection, through jks and wallet

**Comment by daust** [comment]
Can you try using sqlcl on the same machine with the same wallet? To make sure, the wallet works at all.

**Comment by har3653** [comment]
I conected through sqlcl as suggested. Im using version 2.4 of integration tool,  is it possible to connect with this version

**Comment by har3653** [comment]
i tried on another local linux machine and got this error  : Invalid connection string format, a valid format is: "host:port:sid"

**Comment by har3653** [comment]
OK i just managed to connect from my local machine, i had to use newest odbc8 jar and replace it in tomcat/webapps/jasperreports/WEB-INF/lib   and  then restart tomcat. And my link had to be closed with /  (/tmp/wallet/). Il try same on cloud VM

**Comment by daust** [comment]
Not sure that it will work with 2.4.

The support for the autonomous database was added in version 2.7: 
![image](https://user-images.githubusercontent.com/4840057/111968705-c023e600-8af9-11eb-9c51-926e48c5163b.png)

There it should work right out of the box. 

Cheers

**Comment by har3653** [comment]
I conected with 2.4 version from VM on cloud but only works with JKS. On same version of linux but localy it works with oracle wallet.    In all cases odbc8 have to be copied into tomcat/webapps/jasperreports/WEB-INF/lib folder and replace old odbc.I conected with jaspereports 6.5.15 with JKS from windows also.

**Comment by daust** [comment]
Ok, great that you could make it work with 2.4. 

So, we are done here, right? Can I close the ticket?

**Comment by har3653** [comment]
Yes , thank you
