### ISSUE TITLE
application.properties in README.md instead of jasperreports.properties

### ISSUE THREAD

**Issue by dvht** [daust/JasperReportsIntegration#77]
Hi Dietmar,

I helped my colleages today with switching from JDBC to JNDI, but some of the instructions in README.md are misleading.
"configuration" chapter says "jasperreports.properties file", but application.properties is meant.

Regards,
Dirk

**Comment by daust** [comment]
Yeah, I should update the instructions. I hardly use the JNDI integration any more. 

Why did you switch and which version are you using, 2.7.0?

**Comment by dvht** [comment]
Hi Dietmar,

Excuse me for ignoring your question so long.  I lost track of this.  We use JNDI primary for having identical configuration setup over all java web applications.  And, besides, the number of connections is limited and connections already made.  
I can't remember which team asked the question, so I can't say anymore which version they were using.

Regards,
Dirk
