### ISSUE TITLE
Unable to connect to Pluggable Database

### ISSUE THREAD

**Issue by daxlai** [daust/JasperReportsIntegration#83]
I configured JasperReportIntegration on tomcat 10. When i connect it go pluggable database it not connect but when i connect it root container than it connected i checked password and every thing many times but not it not connected. please guide me.
when i connected with my pluggable database my conf/application.property have
[datasource:default]
type=jdbc
name=default
url=jdbc:oracle:thin:@192.168.1.84:1521:xepdb1
username=hll
password=hll

WHEN I CONNECTED ROOT CONTAINER (WHICH IS WORKING)
[datasource:default]
type=jdbc
name=default
url=jdbc:oracle:thin:@192.168.1.84:1521:xe
username=system
password=oracle

**Comment by mikaelkael13** [comment]
Change your url . For pdb, it is not a SID so you have to use '/'  instead of ':' for connecting to a service_name 

[datasource:default]
type=jdbc
name=default
url=jdbc:oracle:thin:@192.168.1.84:1521/xepdb1
username=hll
password=hll

**Comment by daust** [comment]
Thank you, @mikaelkael13 . 

Yes, this is correct. I simply use the standard jdbc url syntax for connecting the database. 
Does it work now?
